spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/playgrounds
    driver-class-name: org.postgresql.Driver
    username: dev
    password: dev

#  jpa:
#    hibernate:
#      ddl-auto: create
